# Generated by Django 3.1.1 on 2020-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdouct_name', models.CharField(max_length=100)),
                ('descriptiom', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
