# Generated by Django 3.1.1 on 2020-10-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdouct_name',
            new_name='product_name',
        ),
    ]
